reqfund/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^add/', views.add, name='add'),
    url(r'^add_action/', views.add_action, name='add_action'),
    url(r'^ag/', views.add_ag, name='add_ag'),
    url(r'^add_ag_action/', views.add_ag_action, name='add_ag_action'),
    url(r'^am/', views.add_am, name='add_am'),
    url(r'^add_am_action/', views.add_am_action, name='add_am_action'),
    url(r'^agent/', views.agent, name='agent'),
    url(r'^medium/', views.medium, name='medium')

 
]

reqfunds/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from reqfund.views import index

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('reqfund.urls', namespace='reqfund')),
]

reqfund/models.py
#encoding=utf-8
from django.db import models

class ReqFundInfo(models.Model):
	req_date = models.CharField(max_length=20, default='')
	req_team = models.CharField(max_length=10)
	req_account = models.CharField(max_length=20, default='')
	rapplicant= models.CharField(max_length=10, default='')
	ragent = models.ForeignKey('AgentInfo', null=True)
	rmedium = models.ForeignKey('MediumInfo', null=True)
	ramount = models.CharField(max_length=5, default='')
	reb_proprotion = models.CharField(max_length=10,default='')
	rpay_way = models.CharField(max_length=2, default='')
	rpayment_date = models.CharField(max_length=20, default='')
	rfund_state = models.CharField(max_length=3, default='')
	rauditor = models.CharField(max_length=10, default='')
	rmanager = models.CharField(max_length=10, default='')
	audit_state = models.CharField(max_length=3, default='')
	extend_add = models.CharField(max_length=20, default='')
	submit = models.CharField(max_length=1, default='')
	isDelete = models.BooleanField(default=False)
	def __str__(self):
		return self.req_team.encode('utf-8')
	
class AgentInfo(models.Model):
	agency_company = models.CharField(max_length=10)
	contract_add = models.CharField(max_length=40)
	bank_account = models.CharField(max_length=20)
	subbranch_name = models.CharField(max_length=20)
	isDelete = models.BooleanField(default=False)
	def __str__(self):
		return self.agency_company.encode('utf-8')


class MediumInfo(models.Model):
	mtitle = models.CharField(max_length=10)
	account_way = models.CharField(max_length=3, default='CPC')
	isDelete = models.BooleanField(default=False)
	def __str__(self):
		return self.mtitle.encode('utf-8')

reqfund/views.py
#encoding=utf-8

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from . import models

def index(request):
	'''reqfund = models.ReqFundInfo.objects.get(pk=id)'''
	reqfunds = models.ReqFundInfo.objects.all()
	return render(request, 'index.html', {'reqfunds':reqfunds})

def agent(request):
	agents = models.AgentInfo.objects.all()
	return render(request, 'agent.html', {'agents':agents})

def medium(request):
	mediums = models.MediumInfo.objects.all()
	return render(request, 'medium.html', {'mediums':mediums})

def add(request):
	agents = models.AgentInfo.objects.all()
	mediums = models.MediumInfo.objects.all()
	return render(request, 'add.html', {'agents':agents, 'mediums':mediums})

def delete(request, id):
	pass

def add_action(request):
	req_date = request.POST.get('req_date')
	req_team = request.POST.get('req_team')
	req_account = request.POST.get('req_account')
	rapplicant= request.POST.get('rapplicant')
	ragent = request.POST.get('models.MediumInfo.objects.get(pk=agentinfo.id)')
	rmedium = request.POST.get('models.MediumInfo.objects.get(pk=mediuminfo.id)')
	ramount = request.POST.get('ramount')
	reb_proprotion = request.POST.get('reb_proprotion')
	rpay_way = request.POST.get('rpay_way')
	rpayment_date = request.POST.get('rpayment_date')
	rfund_state = request.POST.get('rfund_state')
	rauditor = request.POST.get('rauditor')
	rmanager = request.POST.get('rmanager')
	audit_state = request.POST.get('audit_state')
	extend_add = request.POST.get('rmedium')
	submit=request.POST.get('submit')
	models.ReqFundInfo.objects.create(req_date=req_date, req_team=req_team, req_account=req_account, rapplicant=rapplicant, ragent=ragent,
				rmedium=rmedium, ramount=ramount, reb_proprotion=reb_proprotion,rpay_way=rpay_way, rpayment_date=rpayment_date, rfund_state=rfund_state,
				rauditor=rauditor, rmanager=rmanager, audit_state=audit_state, extend_add=extend_add, submit=submit)
	reqfunds = models.ReqFundInfo.objects.all()
	return render(request, 'index.html', {'reqfunds':reqfunds})

def add_ag(request):
	return render(request, 'add_ag.html')

def add_ag_action(request):
	agency_company = request.POST.get('agency_company')
	contract_add = request.POST.get('contract_add')
	bank_account = request.POST.get('bank_account')
	subbranch_name = request.POST.get('subbranch_name')
	models.AgentInfo.objects.create(agency_company=agency_company, contract_add=contract_add, bank_account=bank_account, subbranch_name=subbranch_name)
	agents = models.AgentInfo.objects.all()
	return render(request, 'add_ag.html', {'agents':agents})

def add_am(request):
	return render(request, 'add_am.html')

def add_am_action(request):
	mtitle = request.POST.get('mtitle')
	account_way = request.POST.get('account_way')
	models.MediumInfo.objects.create(mtitle=mtitle, account_way=account_way)
	mediums = models.MediumInfo.objects.all()
	return render(request, 'add.html', {mediums:mediums})

templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>新增</title>
</head>
<body>
<h2>新增请款单</h2>
	<form action="{% url 'reqfund:add_action' %}" method="post">
	    {% csrf_token %}  
		<label>请款日期
	       &nbsp
	    	<input type="date" name="req_date">
	    </label>
	    </br>
	    <label>请款团队
	       &nbsp
	       <input type="text" name="req_team">
	    </label>
	    </br>
	    <label>请款账户
	       &nbsp
	       <input type="text" name="req_account">
	    </label>
	    </br>
	    <label>请款人
	    	&nbsp&nbsp&nbsp&nbsp
	    	<input type="text" name="rapplicant">
	    </label>
	    </br>
	    <label>代理公司
	    	&nbsp
	    	<select id="agent" name="ragent">
    			<option value="">代理配置表</option>
    			{% for agent in agents %}
    				<option value="agent.agency_company">{{agent.agency_company}}</option>
    			{% endfor %}
			</select>
			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
			<a type="button" href='/ag'>新建</a>
		</label>
	   	</br>
	    <label>媒体
	    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
	    	<select id="medium" name="rmedium">
	    	<option value="">媒体配置表</option>
    			{% for medium in mediums %}
    				<option value="medium.mtitle">{{medium.mtitle}}</option>}
    			{% endfor %}
			</select>
			&nbsp&nbsp&nbsp&nbsp
			<a type="button" href='/am'>新建</a>
		</label>
	    </br>
	    <label>金额
	    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		<input type="text" name="ramount" placeholder="RMB">
	    </label>
	    </br>
	    <label>返点比例
	    &nbsp
	    <input type="text" name="reb_proprotion">
	    </label>
	    </br>
	    <label>付款方式
	    &nbsp
	    <select id="payway" name="rpay_way">
    			<option value="垫付">垫付</option>
    			<option value="预付">预付</option>
			</select>
			</label>
	    </br>
	    <label>到账时间
	    &nbsp
	    <input type="date" name="rpayment_date">
	    </label>
	    </br>
	    <label>打款状态
	    &nbsp
	    <select id="paystate" name="rfund_state">
    			<option value="已打款">已打款</option>
    			<option value="未打款">未打款</option>
			</select>
		</label>
		</br>
	    <label>审核人
	    &nbsp&nbsp&nbsp&nbsp
	    <input type="text" name="rauditor">
	    </label>
	    </br>
	    <label>负责人
	    &nbsp&nbsp&nbsp&nbsp
	    	<input type="text" name="rmanager" placeholder="不填默认当前用户中文名">
	    </label>
	    </br>
	    <label>审核状态
	    &nbsp
	    	<select id="paystate" name="audit_state">
    			<option value="未审核">未审核</option>
    			<option value="已审核">已审核</option>
			</select>
		</label>
		</br>
	    <label>后台推广地址
	    	<select name="extend_add">
	    		<option value="rmedium" disabled="">{{extend_add}}媒体对应自动选择</option>
	    	</select>
	    </label>
	    </br>
	    <labe>是否提交今日打款
	       <input type="radio" name="submit" value="是">是
	       <input type="radio" name="submit" value="否">否
	    </label>
	    </br>
	    <input type="submit" value="保存" "onclick="alert('ok！');">
	    	<script type="text/javascript">
				var a='你好';
				alert(a);
			</script>

	    <a href='/index'><input type="button" value="返回"></a>
	</form>
	<!--<script type="text/javascript" src="static/jquery-3.3.1.min.map"></script>
	<script type="text/javascript">
		$(function(){
			$.get('getagt/', function(agt){
				agent=$('#agent')
				$.each(agt.data, function(index, item){
					agent.append('<option value='+item[0]+'>'+item[1]+ '</option>');
				})
			});
		})
	</script>-->
</body>
</html>

templates/add_ag.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>代理配置</title>
</head>
<body>
<h2>新建代理</h2>
	<form action="{% url 'reqfund:add_ag_action' %}" method="post">
		{% csrf_token %}
			<label>代理公司
				<input type="text" name="agency_company">
			</label>
			<br>
			<label>合同地址
				<input type="text" name="contract_add">
			</label>
			<br>
			<label>银行账户
				<input type="text" name="bank_account">
			</label>
			<br>
			<label>支行名称
				<input type="text" name="subbranch_name">
			</label>
			<br>
			<br>
			<input type="submit" value="保存">
			<a href='/add'><input type="button" value="返回"></a>
	</form>
</body>
</html>

templates/add_am.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>代理配置</title>
</head>
<body>
<h2>新建代理</h2>
	<form action="{% url 'reqfund:add_am_action' %}" method="post">
		{% csrf_token %}
		<label>媒体名称
			<input type="text" name="mtitle">
		</label>
		<br>
		<label>计费方式
			<input type="text" name="account_way">
		</label>
		<br>
		<br>
		<input type="submit" value="保存">
		<a href='/add'><input type="button" value="返回"></a>
	</form>
</body>
</html>

templates/agent.html
<!DOCTYPE html>
<html>
<head>
	<title>代理配置表</title>
</head>
<body>
<table class="toolTable" width="200px" cellspacing="0" cellpadding="0" border="" >
<caption>代理配置表</caption> 
	<tr>
		<th>序号</th>
		<th>名称</th>
	</tr>
	
<tbody>
	{% for agent in agents%}
	<tr>
		<td>{{agent.id}}</td>
		<td>{{agent.agency_company}}</td>
	</tr>
	{% endfor %}
</tbody>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script type="text/javascript" scr="static/jquery-3.3.1.min.map"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>首页</title>
</head>
<body>
<ul class="nav nav-tabs">
    <li class='active'><a onclick="javascript:location.href='/add'">新增请款</a></li>
    <li class='active'><a onclick="javascript:location.href='/trush'">回收站</a></li>
    <li class='active'><a onclick="javascript:location.href='/edit'">自定义表头</a></li>
</ul>
    <a style="color: rgb(255,0,255);" href="/index">请款列表</a>
    <a style="color: rgb(255,0,100);" href="/agent">代理配置表</a>
    <a style="color: rgb(255,0,0);" href="/medium">媒体配置表</a>
<table class="toolTable" width="100%" cellspacing="0" cellpadding="0" border="">
<caption>请款列表</caption>
    <tr>
        <th>ID</th>
        <th>请款日期</th>
        <th>请款团队</th>
        <th>请款账户</th>
        <th>请款人</th>
        <th>代理渠道</th>
        <th>媒体</th>
        <th>金额</th>
        <th>返点比例</th>
        <th>付款方式</th>
        <th>到账时间</th>
        <th>打款状态</th>
        <th>审核人</th>
        <th>负责人</th>
    </tr>
<tbody>
    {% for reqfund in reqfunds %}
        <tr>
            <td>{{reqfund.id}}</td>
            <td>{{reqfund.req_date}}</td>
            <td>{{reqfund.req_team}}</td>
            <td>{{reqfund.req_account}}</td>
            <td>{{reqfund.rapplicant}}</td>
            <td>{{reqfund.ragent}}</td>
            <td>{{reqfund.rmedium}}</td>
            <td>{{reqfund.reqfund.ramount}}</td>
            <td>{{reqfund.reb_proprotion}}</td>
            <td>{{reqfund.rpay_way}}</td>
            <td>{{reqfund.rpayment_date}}</td>
            <td>{{reqfund.rfund_state}}</td>
            <td>{{reqfund.rauditor}}</td>
            <td>{{reqfund.rmanager}}</td>
        </tr>
    {% endfor %}
</tbody>
    </table>
</body>
</html>
    

templates/medium.html
<!DOCTYPE html>
<html>
<head>
	<title>代理配置表</title>
</head>
<body>
<table class="toolTable" width="200px" cellspacing="0" cellpadding="0" border="" >
<caption>代理配置表</caption> 
	<tr>
		<th>序号</th>
		<th>名称</th>
		<th>计费方式</th>
	</tr>
	
<tbody>
	{% for medium in mediums%}
	<tr>
		<td>{{medium.id}}</td>
		<td>{{medium.mtitle}}</td>
		<td>{{medium.account_way}}</td>
	</tr>
	{% endfor %}
</tbody>
</body>
</html>